### ISSUE TITLE
Implemented react-bootstrap-tabs fine but having CSS styling issues inside tabs

### ISSUE THREAD

**Issue by Dmon1Unlimited** [freeranger/react-bootstrap-tabs-demo#2]
Hi, I'm fairly new to front end programming so sorry in advance.

I wanted to add two tabs, where both tabs would show different grids (ag-grids) and that's where I stumbled upon your npm node module package.

Below is my code in the body of my GUI:
`		<Tabs contentClass="tab-content-default">
			<Tab className="hello" label="test">
				<SumTable report={this.state.curReport} />
				<FieldSumTable report={this.state.curReport} />			
			</Tab>
			<Tab label="testing">This</Tab>
		</Tabs>	
`

SumTable  and FieldSumTable  are two grids
The tab functionality does work however I'm having issues with the CSS styling now after using the package. Both the grid are cut off. I 've set the height for the Tabs/Tab which was fine, but I can't set the height for my two grids. 

After checking on Chrome developer Tools I noticed that both my grids are wrapped in a new div (which is inside a new div with class "tab-content").

<div>
		<SumTable report={this.state.curReport} />
		<FieldSumTable report={this.state.curReport} />	
</div>

I can't seem to change the CSS styling of this div
e.g. 

.hello div{
	height:92%;
}

Can I get some advice? 
I also noticed my own class names wont appear (i.e. i do no see class name hello in chrome developer tools) Even using you convention contentClass="hello" i still wont see it

Just having the below lets me see my grids again, but I don't think it is wise to make div level changes like this. I don't understand why the above .hello div doesn't work
div{
	height:92%;
}

**Comment by freeranger** [comment]
Hi,

Your best best is to post a link to a deployed github.io site or jsfiddle or similar demonstrating the problem you are having.
This should be the absolute minimum necessary to show the problem - no server side components or complex installs.  If the problem happens with only one grid then just put one grid on there, not two etc.

There could be any number of reasons why your own classes aren't showing up and why you are experiencing other styling issues and this really will be the best way to diagnose rather than you posting code snippets - which don't tell the whole story - and me trying to guess!

thanks

**Comment by Dmon1Unlimited** [comment]
Hi again. i managed to get it looking the way it should. 
Apparently if you are specifying the height as a percent, then you need to make sure all outer elements have a height and that it is also set as a percentage?
Specifying a height for html/body/etc as well as having the below allowed me to see my grids

.tabs{
	height:80vh;	
}

.tab-content, .tab-content-default{
	height:75%;
}

Thanks for the help :)

**Comment by freeranger** [comment]
No problem - thanks for finding the solution yourself :)
